# Classes and Instances Lab (Intro - Classes and Instances)
# Instance Methods Lab (Intro - Instance Methods)
# Instance Variables (OO Ruby - Object Properties)
# Object Attributes Lab (Intro - Object Properties)
# Meowing Cat (Intro - Object Properties)
# Object Initialize Lab (Intro - Object Lifecycles)
# OO Basics (OO Ruby - Object Lifecycles)
# OO Basics with Class Constants (OO Ruby - Object Lifecycles)
# School Domain (OO Ruby - Object Lifecycles)
# OO Counting Sentences (OO Ruby - Object Self)
# Class Variables and Methods (OO Ruby - Class Variables and Methods)
# Puppy Lab (OO Ruby - Object Models)
# Advanced Class Methods (OO Ruby - Object Models)
# OO Barking Dog (Intro - Object Models)
# Email Parser (OO Ruby - Object Labs)
# Anagram Detector (OO Ruby - Object Labs)
# OO Cash Register (OO Ruby - Object Labs)
# Objects Belong To (OO Ruby - Object Relationships)
# Objects Has Many (OO Ruby - Object Relationships)
# Collaborating Objects Lab (OO Ruby - Object Relationships)
# OO My Pets (OO Ruby - Object Relationships)
# OO Kickstarter (OO Ruby - Object Relationships)
# OO Banking (OO Ruby - Object Relationships)
# Objects Has Many Through (OO Ruby - Object Relationships)
# Intro to Inheritance (OO Ruby - Object Architecture)
# Intro to Inheritance Lab (OO Ruby - Object Architecture)
# Intro to Modules (OO Ruby - Object Architecture)
# Refactoring with Modules (OO Ruby - Object Architecture)
# Super (OO Ruby - Object Architecture)
# Mass Assignment Lab (OO Ruby - Metaprogramming)
# Custom Errors (OO Ruby - Metaprogramming)
# OO Triangle (OO Ruby - Metaprogramming)
# Gems and Bundler (OO Ruby - Scraping)
# Scraping Lab (OO Ruby - Scraping)
# Scraping Kickstarter (OO Ruby - Scraping)
# Student Scraper (OO Ruby - Final Projects)
